### ISSUE TITLE
Where  can I find the appendix about the experiment result of NAS-HAO

### ISSUE THREAD

**Issue by Littleyezi** [automl/DE-NAS#1]
Hi, I want to learn about the results of NAS-HAO, where can I find the appendix? thanks~

**Comment by Neeratyoy** [comment]
Hi,

You can find it [here](https://ml.informatik.uni-freiburg.de/papers/20-NASICLR-DE-NAS-supplementary.pdf). And additional materials (slides/video) over [here](https://sites.google.com/view/nas2020/accepted-papers?authuser=0) (tip: search for author names).

Thanks for bringing this to notice. I'll add links to the README. Also, I'll add the contact information of the authors for such queries. I shall close this issue given it's not pertaining to the codebase. 

Cheers!
